- hosts: all
  vars_files:
      - settings-default.yml
  user: pi
  sudo: yes

- include: mosquitto_pi.yaml

#tasks:
#     - name: apt update
#       apt: update_cache=yes
#     - name: apt upgrade
#       apt: upgrade=full