- hosts: all
  vars_files:
      - settings-default.yml
  user: pi
  sudo: yes

  tasks:
    - include: mosquitto_pi.yaml
    #- name: apt update
    #  apt: update_cache=yes
    #- name: apt upgrade
    #  apt: upgrade=full

  handlers:
    - name : restart mosquitto
      service: name="mosquitto" state="restarted" enabled="yes"