# This playbook install the mosquitto broker (http://mosquitto.org).
# Install based on http://jpmens.net/2013/09/01/installing-mosquitto-on-a-raspberry-pi/
# ---
#  curl -O http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
#  sudo apt-key add mosquitto-repo.gpg.key
#  rm mosquitto-repo.gpg.key
#  cd /etc/apt/sources.list.d/
#  sudo curl -O http://repo.mosquitto.org/debian/mosquitto-repo.list
#  sudo apt-get update
#  sudo apt-get install mosquitto
#  sudo /etc/init.d/mosquitto stop
#  vi mosquitto.conf
#   retry_interval 10
#   connection test
#   address 127.0.0.1:1884
#   clientid testBridge
#   cleansession false
#   keepalive_interval 60
#   start_type automatic
#   restart_timeout 30
#   idle_timeout 60
#   try_private true
#   username
#   password
---
- name: install mosquitto repo
  apt_key: url=http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key state=present
- name: install mosquitto repo
  get_url : url="http://repo.mosquitto.org/debian/mosquitto-repo.list" dest="/etc/apt/sources.list.d/mosquitto-repo.list"
- name: install mosquitto
  apt: pkg="mosquitto" state="present" update_cache=yes

- name: edit mosquitto conf
  template: src=mosquitto.conf.j2 dest=/etc/mosquitto/mosquitto.conf
  notify:
    - restart mosquitto
#- name: start mosquitto
#  service: name="mosquitto" state="started" enabled="yes"



