# This playbook install the mosquitto broker (http://mosquitto.org).
# Install based on http://jpmens.net/2013/09/01/installing-mosquitto-on-a-raspberry-pi/
# ---
#  curl -O http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
#  sudo apt-key add mosquitto-repo.gpg.key
#  rm mosquitto-repo.gpg.key
#  cd /etc/apt/sources.list.d/
#  sudo curl -O http://repo.mosquitto.org/debian/mosquitto-repo.list
#  sudo apt-get update
#  sudo apt-get install mosquitto
#  sudo /etc/init.d/mosquitto stop
#  vi mosquitto.conf
#   retry_interval 10
#   connection test
#   address 127.0.0.1:1884
#   clientid testBridge
#   cleansession false
#   keepalive_interval 60
#   start_type automatic
#   restart_timeout 30
#   idle_timeout 60
#   try_private true
#   username
#   password

---
- name: install mosquitto repo key
  apt_key: url=http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key state=present
- name: install mosquitto repo
  get_url : url="http://repo.mosquitto.org/debian/mosquitto-repo.list" dest="/etc/apt/sources.list.d/mosquitto-repo.list"
- name: install mosquitto
  apt: pkg="mosquitto" state="present" update_cache=yes

#- name: stop mosquitto
#  service: name=mosquitto
#           state=stopped
#           enabled=yes

- name: edit mosquitto conf
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="retry_interval 10"
- name: edit mosquitto conf 2
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="connection central"
- name: edit mosquitto conf 3
  #TODO edit with NUC address
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="address 127.0.0.1:1884"
- name: edit mosquitto conf 4
  # TODO edit with pi UID
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="clientid raspiBridge"
- name: edit mosquitto conf 5
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="cleansession false"
- name: edit mosquitto conf 6
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="keepalive_interval 60"
- name: edit mosquitto conf 7
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="start_type automatic"
- name: edit mosquitto conf 8
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="restart_timeout 30"
- name: edit mosquitto conf 9
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="idle_timeout 60"
- name: edit mosquitto conf 10
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="try_private true"
- name: edit mosquitto conf 11
  #TODO edit with real values
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="username pi"
- name: edit mosquitto conf 12
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="password pi"
- name: edit mosquitto conf 13
  lineinfile: dest=/etc/mosquitto/mosquitto.conf state=present create=true line="topic bridge out 2"

- name: start mosquitto
  service: name="mosquitto" state="started"

# TODO Not working ?
- name: auto start mosquitto
  service: name="mosquitto" enabled="yes"



