- hosts: votingboards
  user: pi
  sudo: yes

  tasks:
    - name: $item should be installed
      apt:
        pkg={{item}}
        state=present
      with_items:
        - ntp
        - ntpdate

    - name: restart ntp
      service:
        name=ntp
        state=restarted
        enabled=yes




